### ISSUE TITLE
1 issue and 3 questions ;)

### ISSUE THREAD

**Issue by hemertje** [AdamVig/gandi-dynamic-dns#1]
Hi Adam,

thank you for your nice script and docker file...

Have 1 issue and 3 questions 

1) Tried to update my subdomain A-Record (Wildcard => *) with Docker, in Gandi.net I changed my IP-address with a faulty one, but still after minutes of waiting the IP-address does not get updated with my WAN IP-address...
I assume I must use my Gandi.net Production API key ?
Can you have a look at it? Can I use "*" or should I use "Wildcard"?

2) Would be nice to have a variable time update as parameter, 5 minutes is very fast, 60 minutes is more common to update DNS 

3) Is it possible to update multiple subdomains (RECORD_NAME) in one as multiple parameters?

4) Docker complains about your version "3.7", docker only supports version "2", I understand 3.7 is your update version number?

**Comment by AdamVig** [comment]
Thanks for raising this issue and asking these questions.

1. I have never worked with a wildcard domain before. Based on [the API documentation](https://api.gandi.net/docs/livedns/#put-v5-livedns-domains-fqdn-records-rrset_name-rrset_type), it seems that you should use the name of the record for `RECORD_NAME`, whatever that happens to be.
You should be able to retrieve the record names for a domain with this command:
```shell
export GANDI_API_KEY=12345
export DOMAIN=example.com
curl --header 'Accept: application/json' --header "Authorization: Apikey ${GANDI_API_KEY}" https://api.gandi.net/v5/livedns/domains/${DOMAIN}/records
```
As shown in [the documentation for this endpoint](https://api.gandi.net/docs/livedns/#v5-livedns-domains-fqdn-records), you should see an array of objects with `rrset_name` properties. One of those objects will be the `rrset_name` you're looking for, which you can then use as `RECORD_NAME`.

2. I'll put it on my list to make the update time configurable, but no guarantees that I will get to it any time soon. If you are willing and able to make a pull request, here are some pointers:
- Add an environment variable named something like `UPDATE_INTERVAL` with a default value of "5m".
- Change [this line](https://github.com/AdamVig/gandi-dynamic-dns/blob/9a0b211e226e32aa5de2decb7edba798950d3049/gandi-dynamic-dns#L62) to use the environment variable instead of a hard-coded value.
- Document the environment variable, pointing out that it can be set to any value accepted by `sleep` ([documentation here](https://www.gnu.org/software/coreutils/manual/html_node/sleep-invocation.html#sleep-invocation)).

3. It is currently only possible to update a single domain at a time. I would welcome a pull request for this feature, but I doubt I would add it myself since I don't have a use for it. The workaround is simple: run multiple `gandi-dynamic-dns` containers, each with a different `DOMAIN` and/or `RECORD_NAME`. It's not _efficient_, but the container is so small and the memory overhead is so low that I don't see it being a big issue.

4. It sounds like you have an old version of Docker. See [the Docker Compose documentation](https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix) to figure out what Docker version you would need in order to use Compose version 3.7.
Note that this Docker image has no compatibility constraints that I am aware of: you could use it with any Docker Compose version, I just chose to use version 3.7 in the example I provided in the README.
